imageType:
  Original: {}
  LBP2D:
    binWidth: 0.25
    lbp2DRadius: 1 # 1mm is fake unit, means 1 grid voxel here
    lbp2DMethod: 'default'
    force2D: True
  LoG:
    sigma: [1, 1, 1] # 1mm is fake unit, means 1 grid voxel here
    force2D: True
  Gradient: {}
  Exponential: {}

featureClass:
  firstorder:
    - Energy
    - Entropy
    - Kurtosis
    - Maximum
    - MeanAbsoluteDeviation
    - Mean
    - RobustMeanAbsoluteDeviation
    - RootMeanSquared
    - Skewness
    - Uniformity
    - Variance
  glcm:
  glrlm:

setting:
  binCount: 16
  preCrop: True
